# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 113dc1a9d7c99a86bc866da689b0ec9a7ce24ffca6ffb1059eed196d9bd9ba2de4171f6f90bfd0cdf9fb62fc725f8409c8296b750da2bd8b82678cd05e8abb30

test:
  secret_key_base: 80665b65baca03b80e24f401684312c1587aa065459bfe9da7c65111098b259d881ec613dadc6e7eec3a382ce9bd1d89d122fa691cc34794097d11da74f1cba1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
